### ISSUE TITLE
CSSStyles backed by BufSet don't honor order 

### ISSUE THREAD

**Issue by bs76** [widok/widok#100]
When adding styles, they are not kept in any specific order, which may cause broken styling

This causes problems with frameworks that ordered styles e.g. Semantic-UI, where elements with classes 'ten wide' are rendered ok, but 'wide ten' are not. Classes may also be repeated see http://semantic-ui.com/collections/grid.html#significant-word-order 

(also see http://stackoverflow.com/questions/15670631/does-the-order-of-classes-listed-on-an-item-affect-the-css)

**Comment by tindzk** [comment]
Thanks! Note that you cannot use `cssState` when the order matters. Tags will always be added to the end, but in those situations there is an easy workaround:

```scala
val ch = Var(true)
css(ch.map(if (_) Seq("a", "b") else Seq("b")))
```

**Comment by bs76** [comment]
Thanks for fixing. I'm aware cssState won't work then, but I was wondering if something like cssTransform(when:Channel[Boolean], tr:List[String]=>List[String]) would make sense. When you need to set/unset sequence of styles e.g.: need to replace 'ten wide' in 'teen wide ... . .. .. three wide' by 'six wide', but only in first occurence. Such method would allow to do any transform.

**Comment by tindzk** [comment]
A helper function for setting position-dependent CSS tags could be useful, but it should be more generic than `cssTransform`. It would be helpful if you could provide a use case.

**Comment by bs76** [comment]
Looked at the source and turns out I confused signatures of  def css(tags: ReadChannel[Seq[String]]): and def cssState(state: Boolean, cssTags: String*): T
Having css over ReadChannels is what I was looking for.

**Comment by tindzk** [comment]
Great. Please let me know if you encounter any other problems with Semantic-UI.

**Comment by bs76** [comment]
Yup, I will.
