### ISSUE TITLE
Offer designer-friendly, Lift-style, XHTML design templates?

### ISSUE THREAD

**Issue by sixman9** [widok/widok#106]
Hi,
Would you consider using a 'view-first' (non-mvc) HTML model, similar to that of Scala's [Lift project][1]? 

[Designer Friendly Templates @ Lift][2]

[Building Web Applications with Lift][3] (Dr. Dobbs)

[Asta4d][4] => Java-based "view-first" web-framework, inspired by Lift, built by Astamuse  Ltd, Tokyo (Japan)

Basically, 
1. a 'normal', XML-validating, [X]HTML page or fragment is parsed for specific markup/sections, either by attribute, css, or xml-namespace.  
2. these XHTML fragments are then passed to corresponding Scala code (Snippets in [Lift][1]) as arguments, where the XHTML fragment is inspected and augmented by the Snippet's instructions.  
3. the processed XHTML fragment is replaced in the originating document.  
4. The above promotes 'separation of concerns' and allows (enforces) the visual template(s) to be developed independently of [testable] code.

I think that Widok's reactive nature would really compliment this way of composing applications. For the purpose of SPA's (Single Page Applications), the build process might be augmented to include the XHTML pages/fragments into a single code deliverable (routing internally to named fragments). 

To give a little background, I'm not a web UX dev, moreover, I don't *think* like a web dev, so, using markup libraries like ScalaTags, HAML etc. for HTML is not intuitive to me i.e. how do I mix it with normal HTML templates, for example?. However, I do like the RX/Reactive nature of Widok, it is easier to understand than React or Angular, and I want to create SPA's, [Lift][1] is client server in nature.

[1]: http://liftweb.net
[2]: http://seventhings.liftweb.net/templates
[3]: http://www.drdobbs.com/web-development/building-web-applications-with-lift/240159451
[4]: https://github.com/astamuse/asta4d

**Comment by mkotsbak** [comment]
Have you looked at MetaWeb?: https://github.com/MetaStack-pl/MetaWeb Maybe it provides what you are looking for?

**Comment by sixman9** [comment]
[MetaWeb][1] looks promising, I think I'm going to just use Play's Twirl templating engine to embed HTML pages into my ScalaJS code as pre-populated variables. I can then retrieve the designer-friendly 'real' HTML and update the DOM, while use traditional (old) DOM manipulation techniques via JQuery etc.

It might not be cutting edge, and yes, RX is VERY cool, but I can probably get my head around my rudimentary mechanism.

Thanks anyhow.

[1]: https://github.com/MetaStack-pl/MetaWeb
