### ISSUE TITLE
AnchorBase/Anchor needs target attribute

### ISSUE THREAD

**Issue by drdozer** [widok/widok#116]
I'd like to make an anchor that opens in a new window. That means having something like:

```html
<a href="blablabla" target="_blank">blalba</a>
```

`AnchorBase` has a field `url` that set `href` but doesn't have a field `target`.

Possible fixes:

* Add `.target` to `AnchorBase`
* Add five methods for the four special cases of the target attribute:
  - `openInNewFrame` with `target="_blank"`
  - `openHere` with `target="_self"`
  - `openInParentFrame` with `target="_parent"`
  - `openAtTop` with `target="_top"
  - `openIn(target)` with `target=s"$target"`

**Comment by mkotsbak** [comment]
I would say add .target() with parameter an "enum", just like "sealed trait Clear"

**Comment by drdozer** [comment]
That sounds fine to me. As long as there's an option to supply your own target.

**Comment by mkotsbak** [comment]
Ah, true, it could be a framename: http://www.w3schools.com/tags/att_a_target.asp

**Comment by tindzk** [comment]
Thanks! I implemented it. As per @mkotsbak's suggestion we should release v0.3.0 if everything works as expected.
