### ISSUE TITLE
Exceptions are not throw in widok

### ISSUE THREAD

**Issue by jfilali** [widok/widok#119]

**Comment by mkotsbak** [comment]
Well, first, exceptions must be handled. It is not the job of a tag. Do you suggest that it should propagate somehow? To where? Errors should be handled before the GUI code.

Anyway, Exceptions are not a good match for functional code anyway. Do you have an actual example with exceptions? I would suggest looking into something like Try: http://www.scala-lang.org/api/2.9.3/scala/util/Try.html or http://www.scala-lang.org/api/rc2/scala/Either.html or http://typelevel.org/cats/tut/xor.html

**Comment by jfilali** [comment]
Thank you Marius for the quick response, actually, the problem arise as soon as you define a Exception in : ReadChannel[T],map[U](f: T => U): ReadChannel[U] instead, It is has nothing to do with tags. 

Exceptions are not functional but it was on purpose, the idea was to go fully functional  and keep the management of errors as easy as possible. 

So this is the use case : 

`  tbody(

          tr(
            td( ),
            fg.fromObjectValue("data")
                .fromObjectValue("subject")
                .fromObjectValue("formGroups")
                .asList().map{ c =>
                  td(c.asString())

            }
          )
        )`
I'm mapping over the result of a graphQl query and doing a set of cast and Map get. if i don't find the element i throw an exception .

This is the definition of one of the method : 

` def asString() ={
    if(!self.isInstanceOf[StringValueResult])  throw new ClassCastException(s"Not a String ${self.toString}")
    self.asInstanceOf[StringValueResult].value

  }`

Definitively not functional but make my life easier for a prototype. 

And that code doesn't work.

**Comment by mkotsbak** [comment]
Ok, if it a feature request with ReadChannel, it should be filed in https://github.com/MetaStack-pl/MetaRx

I suggest you let asString return either Option or a Try:
```
def asString(): Option[String] = {
if(!self.isInstanceOf[StringValueResult]) None else Some(self.asInstanceOf[StringValueResult].value)
}
```
and then handle it somehow:
```
                .asList().map{ c =>
                  td(c.asString().getOrElse("Was not a string")
```

I'm not sure if you just want the program to crash? Maybe just output something to the console with println(...) ?

**Comment by jfilali** [comment]
Yes but it would be nicer if i have a uniform way to handle those errors. 

Because look at that function witch is not the simple use case of the String : 

`    def fromObjectValue(attribute : String) : ValueResult = {
      if(!self.asInstanceOf[ObjectValueResult].attributes.contains(attribute))  new Exception(attribute)
      self.asInstanceOf[ObjectValueResult]
          .attributes.getOrElse(attribute,throw new Exception(attribute))
    }`

Really i don't want to handle the error outside of the function otherwise my code is going to be messy.

I look at   https://github.com/MetaStack-pl/MetaRx. Are you guys moving away from widok definitively ? I spoke to Tim Nieradzik and he told me you trying develop a more lightweight library for reactive streams only. 

If you can give me more informations about how to implement that feature i will be more than happy to do a pull request for both libraries.

Thanks

**Comment by mkotsbak** [comment]
I really think you should go and study some more Scala programming. Your code looks nasty (very Java like). I don't understand what you mean by `.attributes.getOrElse(attribute,throw new Exception(attribute))`. If you have more than one source of errors, you should use Option.map/flatMap to handle that case.

Take a look at this: https://tersesystems.com/2012/12/27/error-handling-in-scala/  and http://danielwestheide.com/blog/2012/12/26/the-neophytes-guide-to-scala-part-6-error-handling-with-try.html Also you usually don't use asInstanceOf, but rather pattern matching: https://www.safaribooksonline.com/library/view/scala-cookbook/9781449340292/ch03s15.html

Anyway, the reactive structures are moved to MetaRx. Widok is not abandoned, but maybe not much maintained currently.

**Comment by mkotsbak** [comment]
Btw, there might be some Scala.Js support for GraphQL in the future: https://github.com/sangria-graphql/sangria/issues/64
