### ISSUE TITLE
Publish to maven

### ISSUE THREAD

**Issue by q42mark** [widok/widok#35]
Could you put widok on maven? Seems nice to experiment with :smile: , or is it not ready yet?

**Comment by tindzk** [comment]
Actually, Widok v0.1 is already available on Maven Central. See [TodoMVC](https://github.com/widok/todomvc) for a small example.

Version 0.2 is a complete rewrite and will be released by the end of this week, but you can try it out already. All you have to do is run ``sbt publish-local``. There is a branch in the TodoMVC repository which is compatible with v0.2. Apart from some unimplemented methods, I'd consider it production-ready. Also have a look at the [manual](https://github.com/widok/widok/tree/master/docs/chapters).

Please let me know whether you encounter any pitfalls or potential for improvement.

**Comment by tindzk** [comment]
Widok v0.2.0 was just pushed to Maven Central. The changes are documented [here](http://widok.github.io/manual/widok-v0.2.html#version-0.2).
