### ISSUE TITLE
Code from User Manual doesn't work, here: first reactive programming example

### ISSUE THREAD

**Issue by tomtera** [widok/widok#36]
Dear Tim,

I tried to bring the reactive programming example to work on my machine but faced an error regarding line:
    .show(name.unequal("tux"))
where the compiler complains about: unequal is not a member of Var[String] etc.
Switching to name.!=("tux") does work but is still not fully correct...
Do you have any suggestion, how to implement it correct?

**Comment by tomtera** [comment]
Gotcha, 
i found the answer, 
.show(name.isNot("tux")) should work as written in your very first manual example.
Maybe it should be corrected in the reactive programming-section.
kind regards,
Volker

**Comment by tindzk** [comment]
Thanks! This is already fixed in the repository.
