### ISSUE TITLE
Form validation?

### ISSUE THREAD

**Issue by jn73** [widok/widok#41]
Are there any plans to add form-validation outside of the bootstrap-bindings? If it's not in "the pipe" i will probably try to implement something of my own. Would be a good task to get familiar with the framework.

**Comment by tindzk** [comment]
Yes, this would definitely be useful, especially for those who aren't using the Bootstrap bindings. Perhaps you could try to come up with a generic way and implement ``Validator`` in ``org.widok``?

It would be challenging to cover all different use cases. Therefore, it should be possible to subscribe the validation results as a stream. Then, the user could attach arbitrary callbacks to it, which can be used to log the validation results or to show them in an alert box. Other use cases include rendering the validation results accumulated in one ``div``, or attached to the respective input fields (as in Bootstrap).

I guess, it's best if ``Validation`` was not not bound to any widget logic at all. The code should therefore go to ``shared/src``. This allows for better testing and the same interface could be even used on the server-side. On top of ``Validation`` you can implement special Scala.js validators (in ``org.widok.validators``), like ``Alert`` or ``CSS``.

For some inspiration, have a look at the [Bootstrap implementation](https://github.com/widok/widok/blob/master/js/src/main/scala/org/widok/bindings/Bootstrap/package.scala#L620). Let me know if you need any help.

**Comment by jn73** [comment]
Thanks for your suggestions and pointers. I was also thinking of a low-level validator that publishes the validation results as a stream. I will read up on the bootstrap implementation and start looking at something generic.

**Comment by jn73** [comment]
I have been away on vacation and there haven't been much progress on this. I do have something that works on the client side (validation of forms and their fields, dirty detection etc). It's very similar to the bootstrap implementation. Still needs both thought and work..

What i will be looking at next:

1. simple way of attaching and grouping several validations to the same field/channel.
2. reuse validations on the server side. 
3. some generic way (widget?) that can be used to modify the HTML related to the form/field according to the validation results.

A question:

In the bootstrap implementation the Validation class is a generic class. Although it seems like it's only possible to subscribe to text-channels for an input field. The following won't work for example:

```scala
val age = Var(50)
number().id("age").subscribe(age)
```
Are you planning on making it possible to attach/subscribe to other type of channels? If not, there won't be any need for any other Validations but string-based right? Not that it's a problem to have the Validation class generic anyway, was mostly thinking it would be nice to be able to bind to numeric and date types for example. Or did i miss something?

**Comment by tindzk** [comment]
Thanks for your work on this.

I solved (1) by manually performing multiple checks in the validation functions, but assigning several functions to the same field could be useful to get more fine-grained messages.

(2) should be possible already. I put all my validations in the ``shared`` project and re-use them also on the server-side. However, I have to call the functions manually right now.

(3) will be harder because CSS frameworks deal with validation handling in different ways. For example, in the Bootstrap bindings I'm using implicits for more convenience.

The reason why the number widget expects a string channel is that some browsers allow to insert characters other than digits. If we can come up with a browser-independent approach, I'm open to changes to the interface. We'd also have to think about other HTML5 widgets like date, for example.

For now, you could just use ``biMap()`` to automate the bi-directional conversion from integer to string channels. It's explained [here](https://github.com/widok/widok/blob/master/docs/chapters/07-reactive-programming.md#state-channels).

**Comment by jn73** [comment]
For (1) I have been playing around with a base validation class that has an abstract validate method and then provides a validation message that can be customised using a string that is interpolated with keys that are defined for each validation.

So the idea was to be able to provide a couple of generic validators that would be combined as needed for each field. Each one providing their own (customisable) error messages. It is of course also easy to implement validations of your own.

(2) i have also put the validation classes in the shared project and it would be easy to validate any input using them. I would like a way to validate the input using all validations for that field at once though, so there won't be any repeating of which validations goes for each field. Perhaps something like:

```scala
common:
val usernameValidations = Seq(Required, MinLength(5), MaxLength(30))

client:

val validator = Validator(
  username -> usernameValidations, 
  password -> Seq(required, MinLength(10))
)

server:
def handleSignup(username: String, password: String) = {
  val isValid = usernameValidations.forall(_.validate(username).isEmpty)
}
```

(3) Yes, it would probably be best to leave the CSS-framework integration out of the framework or in bindings when applicable.

Thanks for your comments! And thanks for the reference to biMap - very useful!

**Comment by jn73** [comment]
I haven't had much time to work on this - but I'm getting closer.. What's the best way to submit this for review/discussion? Just a pull-request or should i post code/usage examples here for example?

I also have a question related to reactive/stream aspects..

In my project I use the materializecss framework. I have this support-function that produces a ReadChannel that is used with the Widget::css-method to style the input field as valid/invalid depending on if there is a failing validation for the associated channel:

```scala
  def validState(channel: ReadStateChannel[_])(implicit v: Validator) : ReadChannel[Seq[String]] = {
    v.errors.value(channel).isDefined.map(if (_) Seq("invalid") else Seq("valid"))
  }
```

Now I want to make the channel argument be a vararg - since there might be several validations set for a field. Is there anyway to combine the channels so that the result would be a ReadChannel that returns "invalid" if any of the validation results for the channels yields an error message?

I've been trying foldLeft into a Dict[ReadStatChannel[_], Seq[String]] but haven't been able to map the values to something useful. (i.e merge the values into one channel).

**Comment by tindzk** [comment]
Thanks for the update. Your previous approach already looks pretty decent to me.

The best would be to submit a pull request. I'd be happy to give you some early feedback.

To solve your problem, we'd have to implement a method similar to ``zip()`` that takes multiple channels and aggregates the current values in a ``Seq``. Another approach would be to use ``or()`` and query all current values with ``get`` whenever it produces ``()``.

**Comment by jn73** [comment]
Finally got the code ready for a pull-request. I have an issue with my bindings that is related to a problem that i commented with a "Q: .." in the Validation.md (which i didn't put much effort in until/if the code is accepted).

This code:

```scala
validator.errors.value(username).map(e => div("Validation errror: " + e.mkString(", ")))
```

This will not remove the "validation error" div when the username key is removed from validator.errors dict. Feels like a bug? I will experiment and see if I can come up with an example that is not related to the validation code, and if so create an issue.

**Comment by tindzk** [comment]
Thanks! It looks good. I left a couple of comments in the pull request.
