### ISSUE TITLE
How to design in "reactive" way to filter nodes?

### ISSUE THREAD

**Issue by freewind** [widok/widok#43]
I want to use widok to write some small programs, but sadly found I can't find a `reactive` way for this one: 

**Given some countries with states and cities, when user input some keyword, it will filter all the countries and states and cities, and just show the ones contains that keyword.**

```scala
case class Country(name:String, states: Seq[State])
case class State(name:String, cities: City)
case class City(name:String)

val countries = Seq(
  Country("US", Seq(
    State("AAA", Seq(City("A1"), City("A2"), City("A3"))),
    State("BBB", Seq(City("B1"), City("B2")))
  ),
  Country("China", Seq(
    State("AAC", Seq(City("AC1"), City("AC2"), City("AC3"))),
    State("BBD", Seq(City("D1"), City("D2")))
  )
)
```

The data will be shown as a tree, like:

```
├── China
│   ├── AAC
│   │   ├── AC1
│   │   ├── AC2
│   │   └── AC3
│   └── BBD
│       ├── D1
│       └── D2
└── US
    ├── AAA
    │   ├── A1
    │   ├── A2
    │   └── A3
    └── BBB
        ├── B1
        └── B2
```

When if user inputs `A`, it will show(I use JSON to represent):

```
├── China
│   └── AAC
│       ├── AC1
│       ├── AC2
│       └── AC3
└── US
    └── AAA
        ├── A1
        ├── A2
        └── A3
```

And if inputs `B`, will show:

```
├── China
│   └── BBD
└── US
    └── BBB
        ├── B1
        └── B2
```

And if inputs `3`, will show:

```
├── China
│   └── AAC
│       └── AC3
└── US
    └── AAA
        └── A3
```

And if inputs `n`, will show:

```
└── China
```

And for a `x`, will show empty tree.

I don't know how to design it in `reactive` way. I can use a `Var` for keyword:

```scala
val keyword = Var[String]("")
```

But what should I do for the `countries` and `states` and `cities`? They should also be some kind of streams, and will be filtered based on the value of `keyword`.

The hard part is that a country or state is shown or not, is based on its name, and also its children node. 

I'm reading some documents of `reactive programming`, but can't get the idea in a short time, could you give me some advice?

**Comment by tindzk** [comment]
There are two ways to approach filtering a hierarchical ADT:

1) Re-constructing the entire tree after every input change

```scala
val keyword = Var("")
val tree: ReadChannel[Seq[Country]] = keyword.map { kw =>
  // recursively filter tree
  ...
}
```

2) Hiding nodes that do no match the input (use ``show()``)

To display the tree, you should introduce a function for each of the nodes to do the rendering.

**Comment by tindzk** [comment]
Please reopen if it's still an issue.
