### ISSUE TITLE
Get the list of the tree nodes and each node has a `Var`

### ISSUE THREAD

**Issue by freewind** [widok/widok#46]
This is a difficult problem I've no idea:

```scala
sealed trait Item

case class MyCategory(name: String, filteredProjects: Seq[MyProject], backup: Seq[MyProject], showBackup: Var[Boolean] = Var(false)) extends Item

case class MyProject(name: String, filteredLinkGroups: Seq[MyLinkGroup], backup: Seq[MyLinkGroup], showBackup: Var[Boolean] = Var(false)) extends Item

case class MyLinkGroup(name: String, filteredLinks: Seq[MyLink], backup: Seq[MyLink], showBackup: Var[Boolean] = Var(false)) extends Item

case class MyLink(link: Link) extends Item
```

You can see most of the classes have a `showBackup` field which is a `Var[Boolean]`. There are some ways to change it on UI, and when it's `false`, we should use the `filteredXXX` field, otherwise use the `backup`.

Now I have a tree of several `MyCategory`, like:

```scala
val categories = Seq(
    MyCategory("c1", filteredProjects = Seq(MyProject("p1", ...), MyProject("p2", ...)), backup = Seq(MyProject()), showBackup = Var(false)),
    MyCategory("c2", ...),
    MyCategory("c3", ...),
)
```

Now I want to get a list of nodes from the `categories` tree, like:

```scala
val list = Seq(
    MyCategory("c1", ...),
    MyProject("p1", ...),
    MyLinkGroup("l1", ...),
    MyLink(...),
    MyProject("p2", ...),
    ...
    MyCategory("c2", ...),
    ...
    MyCategory("c3", ...),
    ...
)
```

The list is based on the `showBackup` value of each node, so if its value changes, the who items of whole list will be changed.

I want this list because I want to show it as a list in UI, and can use `up` and `down` key to navigate between them.

Current implementation: 

```scala
  private def getList(categories: Seq[MyCategory]): List[Item] = {
    val EmptyList = List.empty[Item]
    categories.foldRight(EmptyList) {
      case (category, result) => category :: (if (category.showBackup.get) category.backup else category.filteredProjects).foldRight(result) {
        case (project, result1) => project :: (if (project.showBackup.get) project.backup else project.filteredLinkGroups).foldRight(result1) {
          case (group, result2) => group :: (if (group.showBackup.get) group.backup else group.filteredLinks).foldRight(result2) {
            case (link, result3) => link :: result3
          }
        }
      }
    }
  }
```

Since all the `showBackup` values can be changed easily from UI, say from a `checkbox`. When user clicks on a checkbox, the value of `showBackup` of a node is changed, so the list will be changed immediate​ly.

But I don't know how to do this. Do I need to iterate all the `showBackup`s from the tree, and generate the list based on them? But that's a really complex task.

How to recreate the list as soon as any `showBackup` value changes?

PS: for now, I have to do:

```scala
categories.attach { t =>
    def recreateList(): Unit = {
      list := findAllItems(t)
    }
    recreateList()
    list.get.foreach {
      case MyCategory(_, _, _, showBackup) => showBackup.attach(_ => recreateList())
      case MyProject(_, _, _, showBackup) => showBackup.attach(_ => recreateList())
      case MyLinkGroup(_, _, _, showBackup) => showBackup.attach(_ => recreateList())
      case _ =>
    }
  }
```

**Comment by tindzk** [comment]
There are two ways to approach it:

* iterate over all nodes recursively and call ``attach()`` on the ``showBackup`` members
* use a designated data structure to store all nodes for which ``showBackup`` is true

I'd prefer the latter and use a reactive hash set. You can have a look at [TodoMVC](https://github.com/widok/todomvc/blob/master/src/main/scala/org/widok/todomvc/Application.scala), where this is done for the completed tasks. Change your declarations as follows:

```scala
sealed trait Item

class MyCategory(
  val name: String
, val filteredProjects: Seq[MyProject]
, val backup: Seq[MyProject]
) extends Item

class MyProject(
  val name: String
, val filteredLinkGroups: Seq[MyLinkGroup]
, val backup: Seq[MyLinkGroup]
) extends Item

class MyLinkGroup(
  val name: String
, val filteredLinks: Seq[MyLink]
, val backup: Seq[MyLink]
) extends Item

class MyLink(
  val link: Link
) extends Item
```

We're using ``class``es instead of ``case class``es to identify the objects by their addresses. This allows us to store two nodes with the same contents in the set. If you prefer to use ``case class``es instead, you could wrap the values in ``Ref`` objects.

```scala
val showBackup = BufSet[Item]()
```

To listen to any change of ``showBackup``, just subscribe to ``showBackup.changes``. Have a look at the [BufSet API](http://widok.github.io/api/v0.2.0/js/#org.widok.BufSet). I reckon that ``toggle`` may be useful for you, too.

**Comment by tindzk** [comment]
Please reopen if this is still an issue.
