### ISSUE TITLE
How to reference to another `text` without using ID?

### ISSUE THREAD

**Issue by freewind** [widok/widok#47]
```scala
override def view(): View = {
  div(
    text().id("search"),
    button("Focus on search").onClick(_ => /* how to focus on the `text()` without using id `search` */)
}
```

I see in the document, it says reference to another widget with id is discouraged, but I didn't how a proper way.

How can I focus on the `search` input when clicking on the button?

**Comment by tindzk** [comment]
Yes, you could write:

```scala
DOM.getElement("search").get.focus()
```

As written in the manual, this is not the best solution to this problem. However, the only way to access a view outside of ``view()``, is to extract it into a variable. Perhaps we could provide a macro to do it for us in the future. For now, you'd have to write:

```scala
val textField = text()

def view() =
  div(
    textField
  , button("Focus")
      .onClick(_ => textField.rendered.focus())
  )
```

``focus()`` is not provided by ``Widget``, so perhaps you want to submit a pull request adding this functionality?
