### ISSUE TITLE
If I set `persistLauncher := false`, how can I render the page manually?

### ISSUE THREAD

**Issue by freewind** [widok/widok#48]
For some reason, I have to define two `PageApplication`s for two html pages(one for chrome extension popup, the other for the options page), so I can't set `persistLauncher := true` in `build.sbt`, otherwise it will report:

    Cannot write launcher file, since there is no or multiple mainClasses

So I have to set `persistLauncher := false`, but how can I render the pages manually?

**Comment by tindzk** [comment]
It is not possible to define two ``PageApplication``s in the same project as explained in the manual. There are two simple solutions for your problem:

* Define two separate projects with shared code
* Check whether the application is executed as a browser extension in ``PageApplication``, and then instantiate either ``ChromeApplication`` or ``WebApplication`` that define the respective layouts

**Comment by freewind** [comment]
But I successfully defined two `PageApplication` in the same project, with `persistLauncher := false`

**Entry.scala**

```scala
@JSExport("Entry")
object NewEntry extends PageApplication {
}
```

**OptionsPage.scala**

```scala
@JSExport("OptionsPage")
object OptionsPage extends PageApplication {
}
```

Then I create two `launcher.js` for each of html page,

**entry-launcher.js**

```js
this.Entry().main();
```

and 

```js
this.OptionsPage().main();
```

Everything works well :)

**Comment by tindzk** [comment]
As the error message states, Scala.js doesn't know whether to create the launcher for ``NewEntry`` or ``OptionsPage``. If you would like it to generate both launchers automatically, you would need to open an issue [here](https://github.com/scala-js/scala-js).

**Comment by freewind** [comment]
Thanks, but I'm fine if I can create them manually
