### ISSUE TITLE
How to make this code more readable?

### ISSUE THREAD

**Issue by freewind** [widok/widok#52]
I have some links inside a channel:

```scala
val links: Channel[Seq[String]] = ...
```

I want to generate some html like:

```html
<div class="links">
  <div class="link">...</div>
  <div class="link">...</div>
  <div class="link">...</div>
  <div class="link">...</div>
</div>
```

So I write the code like:

```scala
links.map(_.map(div(_).css("link"))).map(div(_).css("links"))
```

The problem is that it's not very readable and hard to construct the same html in mind from the code.

Is there any way to make it a little more readable?

PS: I personally feel this point make it much harder:

```scala
links.map(_.map(div(_).css("link"))).map(div(_).css("links"))
          ^~~~~~
```

**Comment by tindzk** [comment]
Is there a specific reason, why you're using ``Var`` instead of ``Buffer``? For ``Buffer`` there is an implicit that allows you to write:

```scala
val links = Buffer("1", "2", "3")

div(
  links.map { link =>
    div(link).css("link")
  }
).css("links")
```

If you want to stick to ``Var``, I would write the code slightly differently to make its meaning more clear:

```scala
div(
  links.map { l =>
    div(
      l.map { s =>
        div(s).css("link")
      }
    )
  }
).css("links")
```

**Comment by tindzk** [comment]
Please reopen if this is still an issue.
