### ISSUE TITLE
Error while rendering values wrapped in Buffer[Ref[_]] 

### ISSUE THREAD

**Issue by prassee** [widok/widok#54]
I have a code like below 

    case class Issue(name: String, id: Long)
   
    val issues = Buffer[Ref[Issue]]()
    val hasIssues = issues.nonEmpty
    lazy val issuesList = div(ul(issues.map {
        x => li(x.get.id)
    })).show(hasIssues)

    def view() = {
       Inline(issuesList)
    }

If I render the page I'm getting an exception as mentioned below (tried with all browsers).

    [Error] InvalidCharacterError: DOM Exception 5: An invalid or illegal character was specified, such as   in an XML name.
	(anonymous function) (widokapp-fastopt.js, line 1087)

**Comment by tindzk** [comment]
The code looks good to me. I believe that the problem is not related to this snippet. It seems to me that ``widokapp-fastopt.js`` is loaded as an XML file. Would you mind sharing a minimal project, so that I could have a closer look?

**Comment by prassee** [comment]
Please have a look at this repo https://github.com/prassee/widokApp

**Comment by tindzk** [comment]
Thanks. I just checked out the repository, but I don't get the character set error here.

**Comment by prassee** [comment]
how does the pull request wold help

**Comment by prassee** [comment]
will use that and update the ticket :)

**Comment by tindzk** [comment]
Could you guide me through so that I can reproduce the problem? It works fine for me in Mozilla Firefox and Chromium.

**Comment by prassee** [comment]
Iam using Safari in MacOSX

**Comment by tindzk** [comment]
I don't believe it's related to Widok. Would you mind reporting this bug [here](https://github.com/scala-js/scala-js)?

**Comment by prassee** [comment]
I tried this on firefox and it works fine

On Sat, Apr 11, 2015 at 2:19 AM, Tim Nieradzik <notifications@github.com>
wrote:

> I don't believe it's related to Widok. Would you mind reporting this bug
> here <https://github.com/scala-js/scala-js>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/widok/widok/issues/54#issuecomment-91682538>.
>



-- 
*Regards*
*Prassee*
