### ISSUE TITLE
Autocompleted input fields will not update bound channels when tabbed out

### ISSUE THREAD

**Issue by jn73** [widok/widok#58]
Using this testcode:

```scala
case class TestPage() extends Page {

  val name = Var("")

  override def ready(route: InstantiatedRoute): Unit = {}

  override def view(): View = div(
    form(
      label("Username").forId("email"),
      text().id("email").bind(name)
    ),
    hr(),
    span(name)
  )
}
```

When i fill in the username field by using autocomplete in chrome (enter the field and press arrow down or just click the field twice) and then tab out from the field the bound channel is not updated.

When i tab back into the field the channel is updated. This does not happen if the field is focused by clicking on it however.

**Comment by tindzk** [comment]
Good catch. We're triggering a change right now only for the ``keyUp`` and ``paste`` events. I believe, we could also add the ``click`` event [here](https://github.com/widok/widok/blob/master/js/src/main/scala/org/widok/Widget.scala#L27). Is there a preferred way to detect changes in JavaScript?

**Comment by jn73** [comment]
I don't think the click event is relevant - i was just noticing that the change was detected when i tabbed back into the field, but not when focused it by clicking. The change should already have been detected though.

I think that the onblur event should be used here. I tried it and it works for me. I will create a pull-request. Very small, but I need the practice - it's my first :-)

**Comment by tindzk** [comment]
I see. It seems to me that ``keyUp`` doesn't get triggered when using auto-completion. If it works with ``blur``, I'd be happy to accept your pull request.

**Comment by jn73** [comment]
I just realised that even with the `blur` check the same problem still affects other auto-completed fields in the forms. Adding the `change` event solves this problem.

I think that the `change` event would have been sufficient for me (chrome) but from reading up on stackoverflow it is probably a good thing to keep the `blur` check for compability reasons.

**Comment by tindzk** [comment]
Thanks for mentioning ``monitorEvents()``. It's very helpful indeed.

I will add ``change`` to the event list. It's a shame that we need to listen to so many events.
