### ISSUE TITLE
Mapping a dict-value (ReadPartialChannel) to a widget does not remove it when the key is removed

### ISSUE THREAD

**Issue by jn73** [widok/widok#64]
The code below will correctly add a DIV with content "VALUE: some value" when the ADD button is clicked.

But, when the REMOVE button is clicked nothing happens. Shouldn't the widget/div be removed from the dom?

```scala
case class TestPage() extends Page {

  val d = Dict[String, String]()

  override def view(): View = div(
    d.value("key").map(v => div(s"VALUE: $v")),

    button("ADD").onClick(_ => d.insertOrUpdate("key", "some value")),
    button("REMOVE").onClick(_ => d.removeIfExists("key"))
  )

  override def ready(route: InstantiatedRoute): Unit = {}
}
```

**Comment by tindzk** [comment]
``value()`` is actually behaving correctly. You can use ``values`` to get notified when a removal takes place, otherwise you're just listening to the stream of defined values. This should do it:

```scala
d.value("key").values.map {
  case None    => div()
  case Some(v) => div(s"Value: $v")
}
```

**Comment by jn73** [comment]
Ah that makes sense. Thanks :)
