### ISSUE TITLE
How to check if an `Opt` has come value currently?

### ISSUE THREAD

**Issue by freewind** [widok/widok#65]
I want to show a list of users, I can click on them, and only the latest clicked user can have a `selected` class.

My code is simple

```scala
import org.widok._
import org.widok.html._

object Main extends PageApplication {

  val users = Seq(User("Jeff"), User("Lily"), User("Mike"), User("Sarah"))

  val selectedUser: Opt[User] = Opt()

  def view() = span(
    h1("Please select a user:"),
    users.map(user =>
      button(user.name)
        .css("user")
        .cssState(selectedUser.contains(user), "selected")
        .onClick(_ => selectedUser := user)
    )
  )
}

case class User(name: String)
```

But it doesn't work as I expected. 

If a user is clicked, it will have the `selected` class forever. That's because `Channel.contains` says, it will return true forever as long as it has contained the parameter once. (not what I want)

How to fix it? Can I still use `Opt[User]` for `selectedUser`, or do I have to use some other type?

Sample project:  https://github.com/freewind/widok-click-user-demo

----

PS: Nice to pick up widok again, the past 2 months are really busy :(

**Comment by tindzk** [comment]
How about ``selectedUser.values.contains(Some(user))``?

**Comment by freewind** [comment]
No, it doesn't change the behavior

**Comment by tindzk** [comment]
Sorry, I meant ``selectedUser.values.is(Some(user))``.

**Comment by freewind** [comment]
Thanks!
