### ISSUE TITLE
How to use `select`?

### ISSUE THREAD

**Issue by freewind** [widok/widok#67]
I want to create a select with several options. The html version may be:

```
<select>
  <option value="aaa">111</option>
  <option disabled>222</option>
  <option value="ccc">333</option>
</select>
```

Notice the 2nd option has a `disabled` attribute, and other two have `value`.

I see there is a `select` in widok, but I can just use its `options()` methods. Not sure how to do it.

**Comment by tindzk** [comment]
Here is an example:

```scala
val languages = Seq("English", "French", "Spanish")
select().options(languages)
```

**Comment by freewind** [comment]
Sorry the question was updated, how to mark the 2nd one as `disabled`? and how to define the `value` attribute?

**Comment by tindzk** [comment]
I see. This is currently not supported.

Instead of taking ``Seq[String]`` in ``options()``, we could change it to accept ``Seq[HTML.Input.Select.Option]``. ``HTML.Input.Select.Option`` already provides ``enabled()``, which sets the ``disabled`` attribute.

**Comment by freewind** [comment]
Thanks!
