### ISSUE TITLE
How to trigger something when an 'option' is selected?

### ISSUE THREAD

**Issue by freewind** [widok/widok#69]
I'm trying to use a form which has a selection with several options, user can select one to fill the form.

There are two requirements:

1. some of the options are marked as "disabled", they can't be selected
2. when an option is selected, there is a "team" should be selected for creating the user

But with current widok api, I'm not sure how to do it. I tried:

1. `select().options(...)`: the `option.onClick` is not working, and not sure how to do it with `select().onChange(...)`
2. `select().bind(...)`:  not sure how to do with it

The live code: https://github.com/freewind/widok-selection-options-demo/blob/master/src/main/scala/example/Main.scala

You can clone it with current widok `0.2.2-SNAPSHOT` and try

**Comment by freewind** [comment]
question updated, thanks !

**Comment by jn73** [comment]
This works:

```scala
select().options(Seq(Option("one"), Option("two"), Option("three"))).onChange(e => dom.console.log(e.target.asInstanceOf[HTMLSelectElement].value)),
```

It's very "widok'ish" though. It would be nice of one could attach to the select-component, or perhaps bind to have two-way updates of the selection. I guess multiselect would complicate this a bit..

**Comment by freewind** [comment]
Thanks for this workaround, I can use it for now

**Comment by tindzk** [comment]
I slightly changed the API, so that you can bind to disabled options easily.

**Comment by freewind** [comment]
Cool! Thanks
