### ISSUE TITLE
How to bind a keyshort on page?

### ISSUE THREAD

**Issue by freewind** [widok/widok#70]
There is a side bar in my page, and I want to give it a page-scope keyshort to toggle it. I tried but failed.

The html: https://github.com/freewind/fast-links/blob/master/app/index.html

How I bind the keyshort: https://github.com/freewind/fast-links/blob/master/src/main/scala/in/freewind/fastlinks/Application.scala#L110

But the keyshort is not triggered.

I did a little search and found we should bind the keyshort to `document`:

```
document.addEventListener('keyup', doc_keyUp, false);
```

How can I do this in widok?

**Comment by freewind** [comment]
I found the solution: 

```
document.keyUp.attach(event => if (toggleSidebarKey(event)) showSidebar := !showSidebar.get)
```

Notice `keyPress` is not working with Chrome. Can use `keyUp` to avoid it.

**Comment by tindzk** [comment]
Yes, that's the right way to listen for key strokes. You could shorten ``showSidebar := !showSidebar.get`` to ``showSidebar.update(!_)``.

Can I close the issue?

**Comment by freewind** [comment]
Cool, thank you
