### ISSUE TITLE
update or clear

### ISSUE THREAD

**Issue by freewind** [widok/widok#75]
```
val selectedProject = Opt[Project]()

selectedProject.update(p => DataStore.findProject(p.id).orElse(DataStore.firstProject).orNull)
```

I want to update the value of an `Opt`, but in some case `clear` it. But if I use `update` method, I don't know how to clear it, so I use `.orNull` to return a `null` to do it (not sure if correct)

What's the better way to do this?

**Comment by jn73** [comment]
I assume findProject and firstProject both returns Option[Project]? Then this should work:

```scala
selectedProject.set(p => DataStore.findProject(p.id).orElse(DataStore.firstProject))
```

**Comment by freewind** [comment]
The code is not compilable. `set` only accepts an `Option`:

```scala
def set(value: Option[T]) {
  if (value.isDefined) this := value.get
  else clear()
}
```

**Comment by jn73** [comment]
Yep, typo in my code.. should be:

```scala
selectedProject.set(DataStore.findProject(p.id).orElse(DataStore.firstProject))
```

**Comment by jn73** [comment]
Yep, there was a typo in my code.. And i didn't quite think it through :-/ I see what your aiming at now.

I think this could should solve the problem - but there could be a "nicer" way of doing it.

```scala
selectedProject.set(selectedProject.toOption.flatMap(p => DataStore.findProject(p.id).orElse(DataStore.firstProject)))
```

(Haven't compiled it...)

In your first example.. You're setting the Opt value filled with null Opt(null) and that's not what you want (i assume). My example should set the Opt to empty instead.

**Comment by freewind** [comment]
Thanks. Maybe the author can provide another `update` method:

```
def update(f: T => Option[T])
```

**Comment by tindzk** [comment]
I would suggest that we make ``Opt[T]`` inherit from ``ReadChannel[Option[T]]``. Then, we could get rid of ``values`` and ``toOption``. As a side-effect, ``update()`` will behave as requested.

``Opt``'s design has lead to some confusion in the past (see #65) and this change would make it easier to use.

**Comment by tindzk** [comment]
I've implemented the changes as described in the previous comment. Could you please check out the branch [``opt-semantics``](https://github.com/widok/widok/tree/opt-semantics) and give it a try?
