### ISSUE TITLE
Add filtering of Channel by a boolean channel?

### ISSUE THREAD

**Issue by mkotsbak** [widok/widok#79]
Could something like this make sense?:

val queryInput = Var("")
val isQueryValid = queryInput.map(_.trim.length > 2)
val validQuery = usernameQueryInput.filter(isQueryValid)

Then isQueryValid could be reused to mark the field as invalid.

**Comment by tindzk** [comment]
You can use ``partialMap`` (which will be renamed to ``collect`` in the next version):

```scala
val validQuery = queryInput.partialMap {
  case s if s.trim.length > 2 => s
}
```

**Comment by mkotsbak** [comment]
Well, that is probably almost the same as using filter/map?

I solved by extracting the condition:

def isValidQuery(q: String) = q.length > 2
and 
then these:
.map(!isValidQuery(_))
.filter(isValidQuery)

**Comment by tindzk** [comment]
Yes, ``partialMap()`` behaves exactly like Scala's ``collect()`` function. It does ``map(!f(_)).filter(f)`` in one go and is potentially faster. You could compress your example to:

```scala
def isValidQuery(q: String) = q.length > 2
val validQuery = queryInput.partialMap { case s if isValidQuery(s) => s }
```
