### ISSUE TITLE
Add support for dynamic Bootstrap menu generation

### ISSUE THREAD

**Issue by mkotsbak** [widok/widok#82]
If you have a list of elements in a Buffer[Something] and try to use it in a Bootstrap menu:

        NavigationBar.Branch("My elements")(
            elements.map { elem =>
                    Item(elem)
            }
        )

Then you get this compile error:

type mismatch; found : org.widok.DeltaBuffer[org.widok.bindings.Bootstrap.Item] required: org.widok.bindings.Bootstrap.Item

**Comment by mkotsbak** [comment]
I'm not sure exactly why, but this seemed to work!:

elements.buffer.get.map {
...}

**Comment by jn73** [comment]
I haven't used the bootstrap bindings but it looks like that the NavigationBar.Branch only works with Bootstrap.Item*. When you map the Buffer you get a DeltaBuffer with your mapped values. The DeltaBuffer includes information of modifications in the buffer (add/delete/update) and there doesn't seem to be any code in the bindings to act on these changes - like there is for regular HTML nodes in widok.

elements.buffer.get.map works because you get a "snapshot" of the buffer and map the values to Items. It won't reflect changes in the buffer though.

**Comment by mkotsbak** [comment]
The strange thing is that it actually was updated with the changes in the buffer!

**Comment by jn73** [comment]
Umm.. that was unexpected - to me anyway :) You didn't have anything outside that code that caused the whole widget to re-render?

**Comment by mkotsbak** [comment]
Well, the NavigationBar is actually a list, so maybe the magic there is injected through the workaround.

**Comment by jn73** [comment]
I tried to reproduce this:

``scala
  val b = Buffer("a", "b")

  b.changes.attach(println)

  override def body(route: InstantiatedRoute): Future[Widget[_]] = Future.successful{
    div(
      NavigationBar(
        NavigationBar.Branch("test")(b.get.map(Item(_)): _*)
      ),
      a("add").onClick(_ => b += "c")
    )
  }
```

When i click "add" there is a console log that shows that "c" is being added to the buffer, but the navbar branch still only shows Items for "a" and "b". This is on the 0.3-branch.

**Comment by mkotsbak** [comment]
But I use "elements.buffer.get.map", not "elements.get.map" in the last released version. It might be caused by .buffer gives access to the internal variable?

**Comment by jn73** [comment]
It looks like calling .buffer only creates a copy of the Buffer so that shouldn't change anything.

**Comment by mkotsbak** [comment]
I think I know why it was updated. It is in a header of the pages, and after I added the element, I changed to another page, probably giving a rerendering of the menu.

**Comment by mkotsbak** [comment]
Still it does not work for BufSet. It probably need the same implicit conversion.

**Comment by mkotsbak** [comment]
To avoid duplicates, but that is probably a quite bad idea and should only happen now during testing.

**Comment by tindzk** [comment]
Have you thought about ``Buffer.distinct``?

**Comment by mkotsbak** [comment]
That might be a workaround yes.
