### ISSUE TITLE
Bootstrap Collapse button not working

### ISSUE THREAD

**Issue by mkotsbak** [widok/widok#83]
The NavigationBar.Toogle() button does not actually open the menu when clicked. This seems to be caused by missing HTML properties:

  data-toggle="collapse" data-target="#myNavbar">

**Comment by mkotsbak** [comment]
Workaround:

NavigationBar.Toggle().attribute("data-toggle", "collapse").attribute("data-target", "#CollapseNavbar"),

and:
NavigationBar.Collapse(
...
).id("CollapseNavbar")

**Comment by tindzk** [comment]
Widok doesn't rely on any external JavaScript libraries. I reimplemented some Bootstrap JavaScript components, but a few features are still missing (such as ``Toggle``).

**Comment by mkotsbak** [comment]
Ah, japp, the workaround also involved adding bootstrap.js to the launch web page...

But how would it be implemented natively without any HTML element references?

**Comment by tindzk** [comment]
The problem is that [``Toggle()``](https://github.com/widok/widok/blob/master/js/src/main/scala/org/widok/bindings/Bootstrap/package.scala#L288) always sets the ``collapsed`` CSS tag.

If you have some time, you could modify it to something similar as [``Branch``](https://github.com/widok/widok/blob/master/js/src/main/scala/org/widok/bindings/Bootstrap/package.scala#L303).

**Comment by mkotsbak** [comment]
Hmm, you mean "collapsed" on the toggle button? I don't think changing that would affect the menu to be collapsed as they are separate.

But to do it as Branch, that would require the button to be part of "Collapse" to have the link to it?

**Comment by tindzk** [comment]
Ok, in that case you could define this flag in your code: ``val collapsed = Var(true) ``

Then add a method to ``Toggle`` as well as ``Collapse`` that listens to it. Also have a look at the Bootstrap sources to see if you need to do any other DOM manipulations.

**Comment by mkotsbak** [comment]
Japp, "collapsed" could be an argument to both.
