### ISSUE TITLE
Widget.show() is not getting initial state from combined channel

### ISSUE THREAD

**Issue by mkotsbak** [widok/widok#87]
Seems like show(someBooleanChannel) is not getting the initial state (flushed?) from the channel, so it does not behave as expected when the widget should not initially be visible (channel is false).

I see it is implemented here as attach(): https://github.com/widok/widok/blob/07fcb1d561d772dee926b48bcbaeb8866ee823cc/js/src/main/scala/org/widok/Widget.scala#L456

**Comment by mkotsbak** [comment]
Ok, now I think I see what is wrong. I see that the combined channel is set up to produce() when one of the input channels changes at: https://github.com/MetaStack-pl/MetaRx/blob/14f4c46a029a785b9c95426da0cebdb674b6c1fd/shared/src/main/scala/pl/metastack/metarx/Channel.scala#L621

but it is not producing the current value when show() triggers attach() which calls flush on the channel at https://github.com/MetaStack-pl/MetaRx/blob/14f4c46a029a785b9c95426da0cebdb674b6c1fd/shared/src/main/scala/pl/metastack/metarx/Channel.scala#L111

**Comment by mkotsbak** [comment]
So maybe after line https://github.com/MetaStack-pl/MetaRx/blob/14f4c46a029a785b9c95426da0cebdb674b6c1fd/shared/src/main/scala/pl/metastack/metarx/Channel.scala#L111 there could be a res.produce(get(), other.get()) ?

**Comment by mkotsbak** [comment]
Or maybe it should use forkUniState() instead with onFlush

**Comment by mkotsbak** [comment]
Hmm. UniChildChannel needs just one parent, so maybe to get this flushing to work up through combine() maybe some refactoring is needed?

**Comment by tindzk** [comment]
Thanks! It is a bug indeed. I have fixed it in [this commit](https://github.com/MetaStack-pl/MetaRx/commit/cb38af367b225798d5fddc28c520e015d3a932ef). Now it also takes a ``ReadChannel`` as per your suggestion.

**Comment by mkotsbak** [comment]
Nice, as this is a major bug, maybe consider a new version of both modules?

**Comment by mkotsbak** [comment]
Also, could it maybe be moved to ReadChannel from StateChannel now, so both parties could be readchannels?

**Comment by tindzk** [comment]
Good idea. I moved ``zip()`` to ``ReadChannel``. I'd prefer to release a new version of MetaRx after some more changes.

**Comment by mkotsbak** [comment]
Okay, great!

**Comment by mkotsbak** [comment]
Solved in MetaRx, but absolutely not in Widok, as it depends on a version without the fix. Either let it depend on SNAPSHOT or release a new MetaRx version to solve it here.

**Comment by tindzk** [comment]
Let me first implement #3 and #13 in MetaRx. Then I'll release a new version. But it will have to wait until tomorrow I'm afraid.

**Comment by tindzk** [comment]
Fixed in the above referenced commit.
