### ISSUE TITLE
Ability to get current route

### ISSUE THREAD

**Issue by mkotsbak** [widok/widok#90]
It is possible to get current active page, but not the route/parameters.

It would be nice to get both to know which Bootstrap menu item to mark as active, as more than one might use the same Page with different parameters.

**Comment by tindzk** [comment]
Do you need the instance of the current page?

**Comment by mkotsbak** [comment]
Well, what I really want is to compare the current page/route with the InstanciatedRoute it was activated with.

**Comment by tindzk** [comment]
If you need the current page, you can access ``currentPage`` on ``Router``. To get the instance to ``Router``, you need to define a custom [``Application``](https://github.com/widok/widok/blob/master/js/src/main/scala/org/widok/Application.scala#L12).

**Comment by mkotsbak** [comment]
Yes, I've done that, but I need to distinguish same page with different parameters. I set up the menu dynamically, some points to the same page with different parameters. Then I want to set .active() according to which page (Instantiated route) is active.

**Comment by tindzk** [comment]
Would it be helpful to offer the arguments of the route as channels? Then you could easily listen to value changes. You may also want to have a look at #19.

**Comment by mkotsbak** [comment]
Absolutely, as the Item.active() takes a ReadChannel[Boolean].

Yes, I've seen that. Something should be done about the router, to incorporate some of the features of the React-SJS router V2.

**Comment by mkotsbak** [comment]
But actually in this case, I really just need to compare it to an InstantiatedRoute instance, but that could be reactive:

Item(...).active(app.router.currentRoute.is(currentItem.route))

**Comment by tindzk** [comment]
I see. All you would have to do is add ``currentRoute`` [here](https://github.com/widok/widok/blob/master/js/src/main/scala/org/widok/Router.scala#L88) and set its value in [``render()``](https://github.com/widok/widok/blob/master/js/src/main/scala/org/widok/Router.scala#L121).

[scalajs-react's router](https://github.com/japgolly/scalajs-react/blob/master/extra/ROUTER2.md) looks interesting. We should definitely think about incorporating some of its concepts.

**Comment by mkotsbak** [comment]
Yes, I think we should do that.
