### ISSUE TITLE
Support for Scala Js fiddler / Scala Fiddle

### ISSUE THREAD

**Issue by mkotsbak** [widok/widok#94]
Having it running in the Fiddler: https://github.com/lihaoyi/scala-js-fiddle would be a nice way for quick demonstation of Widok.

Since it seems it is not possible to add extra dependencies there: https://github.com/lihaoyi/scala-js-fiddle/issues/23 a workaround is to fork the project and add them there, and host it somewhere, given the license allows: https://github.com/lihaoyi/scala-js-fiddle/issues/22

**Comment by mkotsbak** [comment]
Finally it seems we can have some progress here by the new ScalaFiddle (based on the old scala-js-fiddle): https://beetta.scalafiddle.io/

I'm currently trying with this full script:

```
import fiddle.Fiddle, Fiddle.println
import scalajs.js

import org.widok._
import org.widok.html._
import pl.metastack.metarx.Var

@js.annotation.JSExport
object ScalaFiddle extends PageApplication{
  // $FiddleStart

    println("<div id='page></div>'")

    val name = Var("")
    val hasName = name.map(_.nonEmpty)

    def view() = div(
      h1("Welcome to Widok!")
    , p("Please enter your name:")

    , text().bind(name)

    , p("Hello, ", name)
        .show(hasName)

    , button("Change my name")
        .onClick(_ => name := "tux")
        .show(name !=== "tux")

    , button("Log out")
        .onClick(_ => name := "")
        .show(hasName)
    )

  def ready() { }
  // $FiddleEnd
}
```

ScalaFiddle has got support for MetaRx and Widok, and currently it fails because of a version mismatch of scalajs.dom, but it might be possible that ScalaFiddle is fixed to solve that.

**Comment by mkotsbak** [comment]
Working fiddle: https://beetta.scalafiddle.io/sf/iykWoY/0 Or a bit more compact: https://beetta.scalafiddle.io/sf/7hgbEt/2

Then remaining is just to embed it on the homepage.

**Comment by mkotsbak** [comment]
Added PR to homepage: https://github.com/widok/widok.github.io/pull/4

**Comment by tindzk** [comment]
Thanks! I merged your pull request.
