### ISSUE TITLE
Support && between Widget and Boolean

### ISSUE THREAD

**Issue by mkotsbak** [widok/widok#96]
I saw this pattern in React:

          {hasTodos &&
            <TodoList
              todos={this.props.viewer.todos}
              viewer={this.props.viewer}
            />
          }

The same could be added as a shortcut in Widok to optionally include a widget. Really the same as .show(boolean)

**Comment by tindzk** [comment]
I think it is confusing because you would expect that the second operand of `&&`  is a Boolean value (or channel) as well.

**Comment by mkotsbak** [comment]
I agree now. It probably fits better in the typeless wild west of JS than the typesafe Scala environment.
